### ISSUE TITLE
Restore Flowers module

### ISSUE THREAD

**Issue by labpaw** [GrowthcraftCE/Growthcraft-1.7#102]
Was requested [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10?comment=89). Sounds like interesting request. Latest available module version is for Minecraft 1.5.2 located [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286298-growthcraft-jul-15-2014-proper-1-7-10-release) under Flowers spoiler. What do you think guys? Also, future flower related stuff can be added to this module.

**Comment by Ar97x** [comment]
Somebody have already replied this guy, that bees offer almost the same
functionality of the flowers module. We could try to remake it, but as a
garden module, would be way more insteresting.

**Comment by Sunconure11** [comment]
The reason I thought flowers might be redundant due to the amount of changes 1.7 brought to flowers. However, I suppose a garden module can be done.

**Comment by ghost** [comment]
flowers can easily be grown using bonemeal. is kinda nub but works really fast. also there are plenty of mods like botania that add 1 million flowers that you do just that grow flowers forever. ha

**Comment by IceDragon200** [comment]
@trollworkout On that note we should add support for botania flowers in the bees module

**Comment by Sunconure11** [comment]
That was suggested by me in the past, but, I think it would be best to have a magic bee hive that can grow them.

**Comment by ghost** [comment]
@IceDragon200  i can test out botania too if you need

**Comment by tehFoxx0rz** [comment]
The main value I see to this is the lovely bushes.  Perhaps they could be added to the bees module, if not a separate garden module (which would be great too)?

**Comment by ghost** [comment]
@IceDragon200  Ok. I notice the bee box spreads flowers around it. So I assume you can grow flowers using the bee box?

**Comment by ghost** [comment]
@IceDragon200 you can easily add support for ANY flowers including Botania  by adding a bit of code that searches for any block around it that extends growable? that contains a specific string name pulled from config file 

// bee boxes will also use any plants around it that contain the following strings
"Additional Bee Box flowers"=Flower, Shimmerleaf

This will make bee boxes kick in that extra bit of code which will look for any other plant block around it that has the string "%Flower%" or "%Shimmerleaf%" (% =is anything). Since all Botania flowers have the word flower in it then all of it's flowers are automagically supported.

This way EVEN if you don't have the mod it will still work and any mod can potentially be supported by growthcraft. BiblioCraft uses this system and it works quite well.

What do you think?

**Comment by Ar97x** [comment]
I think we already have a Botania compat, but I'm not so sure. Check the
closed issues.

**Comment by IceDragon200** [comment]
I think we can safely drop this idea, the existing User API allows users to add custom flowers for use in the bees module.
