### ISSUE TITLE
Established a standardized test case for Single Player and SMP releases

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#109]
Title says it all ... all of our testing has been with single player. I'd like to have a wiki page with a standard list is test items that one of us can run through for single and multiplayer releases.

**Comment by MidnightsFX** [comment]
I am sure you guys have some unit tests that probably hit a fair amount of this stuff. But if I was very unsure of how stable this mod was and how it would work in a modpack or otherwise this is what I would test.

**Generation**
- Check to make sure that beehives generate, checking vanilla trees and modded trees
- Check village generation, make sure that when removing or adding blocks to support the generation odd things don't happen
- Check bamboo and apple generation, make sure that they generate in biomes listed in the config file and those biomes translate properly.

**Ore Dictionary**
- Check to make sure that apples generated can be used to craft apple recipes
- Check that bamboo sticks can be used in vanilla and modded crafting recipes
- Check that bamboo can be used as a wood block and slabs in crafting recipes if desired
- Check that fluids from growthcraft can move through modded fluid containers, also check placement of liquids does not break things.
- Check if growthcraft recipes can be crafted with ore dictionary woods, (barrel, fruit press, fish trap, bee box)
- Check ore dictionary support for growthcraft rope and minecraft rope?

As far as test cases It would be ideal to test this on a number of different java versions and current, past and possible newer versions of forge in single player, LAN and with a dedicated server.

**Single Player - Target Forge Version and Java Version**
- Check ore dictionary support of growthcraft recipes and modded/vanilla support for growthcrafts ore dictionary sticks/planks
- Check village generation and bamboo/apple generation in biomes

**LAN & Dedicated Server - Target Forge Version and Java Version**
- Check liquid placement, usage and the ability to move through modded containers - check sync with other players
- Check Fishtrap usage and verify that the server keeps the chunk loaded/unloaded when desired.
- Grow crops with bonemeal, check growth stages are propagated to other clients properly and check multiple people bonemealing a plant
- Test that existing worlds with the previous version of growthcraft still function properly.

**Suggested Mods**
- Buildcraft
- Forestry
- Thaumcraft
- BetterWorldGen / Highlands / BiomesOPlenty / BiomesXL / EnhancedBiomes / RealisticWorldGen

**Comment by spannerman79** [comment]
> stated java version and forge version

Already done; Forge 1448 (10.13.4.1448). Java; 7 and 8.

Most mod devs follow whatever is the recommended forge version is, and right now thats 10.13.4.1448

Edit:  Its even in the [README.md](https://github.com/Alatyami/Growthcraft-1.7/blob/development/README.md)

**Comment by MidnightsFX** [comment]
Ok I removed the section stating the tests should target a specific forge build and java revision.

Also mentioned that the mod should be tested with worlds that used the previous version to check that upgrades does or does not break existing worlds.

**Comment by IceDragon200** [comment]
@Alatyami @MidnightsFX @spannerman79 https://github.com/Alatyami/Growthcraft-1.7/issues/130
I've posted a handful of test builds of the latest development branch

**Comment by MidnightsFX** [comment]
Sounds good, I will likely get a chance to do some testing tomorrow and
report back on the results.

**Comment by MidnightsFX** [comment]
@IceDragon200 Sorry about the delay in this, I didn't get a chance to look at this yesterday but should this evening. Is there a place I can check the change-list for Build f4d34f4 ?

**Comment by IceDragon200** [comment]
@MidnightsFX https://github.com/Alatyami/Growthcraft-1.7/compare/8d5ae3e...f4d34f4

**Comment by MidnightsFX** [comment]
Ok things are looking pretty nice so far. I really like the improved bee-boxes. Also is that a new model with the press?

Anyways, issues!
- Bee gen seems to be a little odd, I am seeing very, very few bee hives generating even when increasing the chance in the config.
- malice, greatwood and silverwood hives are enabled even if thaumcraft is not installed, not sure if that's intended.
- All growthcraft liquids are white in mod-tanks

Still gotta test these
- Multiplayer stuff
- Buildcraft/growthcraft wrenchings
- Null items/null item recipes
- Forestry/other mod flowers

These Look good.
- Liquids look good so far.
- Bamboo gen looks good.
- Fishtraps and brewing looks good.
- Ore dictionary things look good
- Apple tree gen looks good
- Bee gen looks good (but seems to have a reaaaaalllly low chance of spawning?)

I will get some more testing done tomorrow.

**Comment by IceDragon200** [comment]
@MidnightsFX Bee spawning stuff `[Higher -> Slower]`, the higher you set the rate, the less likely they'll spawn. Their world gen is the opposite, the higher you set the density the more likely they'll spawn

Malice, Greatwood and Silverwood bee boxes will exist regardless if their related mod exists, you won't be able to craft them, I'll disable them later, since we still need to add the Forestry Boxes :package:

**Comment by IceDragon200** [comment]
@MidnightsFX You wouldn't mind testing the latest build, added a few new config options for #132

**Comment by MidnightsFX** [comment]
No problem, I'll take a look at it later tonight. Also I noticed that
growthcrafts liquids all look white in buildcrafts liquid tanks, I was
planning on providing more information on that later if needed.

**Comment by PitchBright** [comment]
Also, the fluid amount seems off, when placed in tanks.  This was 1 bottle of Ale: http://imgur.com/FgSv6IL

**Comment by MidnightsFX** [comment]
@MidnightsFX - reminding myself to look at this again with #130 again (just gotta stop playing fallout...).

**Comment by MidnightsFX** [comment]
@IceDragon200 With commit 8fc3352 - Build 8322f80 Liquids still look odd in any mod containers they go into. But so far the amount is looking better, I still need to test railcraft though as @PitchBright did. Also still not seeing a lot of beehives with a spawn setting of 1.

I didn't see any nether things. But, the config was showing up.

Keep up the good work! :+1:

**Comment by IceDragon200** [comment]
@MidnightsFX I had to report a fluid tank issue to Buildcraft, you may need to report the liquids to other mods as well, Growthcraft liquids MUST be rendered with their fluid color.

None of the Nether options are available yet, the config option is there, so I don't have to add it later,
but #66 is still in progress.

Beehives, I'll look into it later today after work, you may be having terrible luck though
