### ISSUE TITLE
Move to an organizational github repo

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#149]
What do you think about moving to growthcraft/Growthcraft-1.7 repo?

**Comment by IceDragon200** [comment]
@Alatyami I was going to ask for the same thing!

That would things much easier

**Comment by labpaw** [comment]
Are you guys talking about creating Growthcraft Team organization? Something like this: https://github.com/SleepyTrousers right? Would be cool definitely.
Also, I would suggest you to remove version number from repository name and instead of that use branching system. So, 1.7 branch will be for 1.7.10 MC version, 1.8 branch for 1.8.(8) and so on.

**Comment by Alatyami** [comment]
Yes, that's what I am thinking ....

**Comment by spannerman79** [comment]
> Also, I would suggest you to remove version number from repository name and instead of that use branching system. So, 1.7 branch will be for 1.7.10 MC version, 1.8 branch for 1.8.(8) and so on

Agreed.

> What do you think about moving to growthcraft/Growthcraft-1.7 repo?

It would be easier to give access to people to edit/add to the wiki here on Github as well

**Comment by Alatyami** [comment]
Going to be moving the repo today ...

**Comment by Alatyami** [comment]
https://github.com/GrowthcraftCE

**Comment by spannerman79** [comment]
Cool. Don't forget to invite certain people hint hint :wink:

**Comment by Alatyami** [comment]
It has been moved ... sending out invites now ...

**Comment by labpaw** [comment]
@Alatyami is it possible to rename repository? I would suggest to rename it to just Growthcraft (without version number).
