### ISSUE TITLE
[SUGGESTION] Thaumcraft Golems should harvest crops

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#154]
While they harvest to some degree (I.E pick up apples that fall), I think that Thaumcraft Golems should harvest crops from this mod, as long as they are in reach.

**Comment by IceDragon200** [comment]
@Sunconure11 We registered some of them, like hops and grapes I think

This is from the Grapes thaumcraft integration 

``` java
FMLInterModComms.sendMessage("Thaumcraft", "harvestStandardCrop", GrowthCraftGrapes.grapeBlock.asStack());
```

**Comment by ghost** [comment]
what about crops like rice with order upgrade would they auto plant rice crops?

there are a few odd ones but i'd like to experiment see what works or doesn't work. i use golems a lot.

**Comment by Sunconure11** [comment]
That could be a good idea.

Maybe they could also work on most nether crops, and if an aqua upgrade is installed, they can work on time-based crops, such as agave and thistle.

**Comment by ghost** [comment]
@Sunconure11  aqua gives improved sense right? that would make sense. in fact if the golem has order and aqua can harvest and also replant time crops.

**Comment by Ar97x** [comment]
That sounds amazing. I'm a complete newbie to Thaumcraft so you guys will
need to teach me XD

**Comment by ghost** [comment]
@Ar97x  I have it installed and i can easily test things out for 1.7.10.

**Comment by ghost** [comment]
i am doing some golem tests right now using growthcraft crops

DECANTING golem core (moves fluids around normally used to supply cauldrons with water but other uses are possible)
- does NOT work on rice paddies. they don't know rice paddies accept or require water.
- WORKS on growthcraft brewing cauldron. it supplies it with water. but it doesn't know that it can take liquids from the cauldron.
- WORKS on barrels . 

EMPTY and FILL golem core
- apparently don't know how to use any growthcraft  machinery

HARVEST golem core
- does not know how to replant rice. rice replanting is very tricky because it requires filling the area with water then replanting. it should only replant if the proper seeds drop but i think it doesn't know the rice seeds 

@Ar97x  @Sunconure11  @IceDragon200

**Comment by ghost** [comment]
@IceDragon200  @Sunconure11  @Ar97x 

so I tested the grapes and seems the golem harvests the trunk thinking it's the mature crop instead of actually harvesting the grapes themselves. 

hops may suffer the same issue. 

it will not replant anything since for some reason no seeds drop when the golem harvests any part of the grape vine although when i harvest seeds do drop. i wonder if is seed drops from breaking grapevine is coded to the player only.

**Comment by IceDragon200** [comment]
Any Thaumcraft coding experts on this topic?

**Comment by Sunconure11** [comment]
Not really, but, you might be able to find the API still.

Here it is:

https://github.com/Azanor/thaumcraft-api

**Comment by IceDragon200** [comment]
@Sunconure11 We already include the [API](https://github.com/GrowthcraftCE/Growthcraft-1.7/tree/development/api/thaumcraft)

**Comment by Sunconure11** [comment]
Maybe ask some devs of some thaumcraft addons on 1.7.10 I guess.

**Comment by hron84** [comment]
@Sunconure11 I strongly recommend you to talk with @InfinityRaider about TC integration since Agricraft had almost same issues that you suffer from. Also, Grapes/hops needs more proper integration, I fear standardCrop is not the best since it means the golem will break the block via left click instead right-click on them because this is how golems harvest crops. Also, ensure the stem blocks are not registered as a valid harvestable block. 

About rice paddis: I bet these stuffs needs to be a proper fluid containers to decanting golems use it, or you should provide a machine that can refill these stuff with water without actually using a bucket.

Same for all brewing machinery, provide a proper tank interfaces to let golems interact with them. my current solution is I extract fluids from the machines with EnderIO Tanks, and golems interact with the tank instead of the machine. Check these tanks and provide all interfaces on machinery. 

Hop/grape workaround: configure USE golems to right click on the grape/hop crops, it should work as player right clicking. Collecting golems should collect the drops properly.

**Comment by InfinityRaider** [comment]
I'm not sure if its any value to you but TC golems also used to break my crops for no reason, until I sat down had a look at the behaviour with some breakpoints and figured it out. I don't know the specifics, but the TC golems check the bonemeal methods before getting to the code for right-click harvesting.
There are two methods in IGrowable returning a boolean, if one of them returs false (bonemeal not useable), the golem assumes its a regular, mature plant and breaks it.
I worked around this by allowing bonemeal form that method always and instead deny bonemeal from within the onBlockActivatedMethod(), it's a workaround and it might not be 100% failsafe for all cases of bonemeal usage, but it fixed the TC golem behaviour.

**Comment by IceDragon200** [comment]
@InfinityRaider In our case, TC golems don't understand our unusual crop growth (Grapes, Hops, Rice) and require some special attention, I skimmed the thaumcraft api but didn't find any interfaces for aiding the golems in understanding how to reap grapes, plant rice or even fill the paddies.

Thanks for the heads up though :)

**Comment by IceDragon200** [comment]
@hron84 Our devices/machines provide all their fluid tank information, however I block certain fluid tanks from being emptied or filled (You can't fill a Brew Kettle's secondary tank), I think I'll need to go over these blocks and double check the filling/draining methods to make sure they work as expected.

Grapes should be obtainable via breaking, or right clicking so golems have it alright, they should also be able to break rice, as long as it's mature.

Hops must be picked (right click), so that will require some finetuning

**Comment by hron84** [comment]
About the grape problem: can you make a grape block slighly different from the stem block (e.g. in metadata)? Golems are a bit dumb, they may not fully understand the difference between the stem block and the grape block.

**Comment by hron84** [comment]
@IceDragon200 the rice paddies are also fluid tanks?

**Comment by IceDragon200** [comment]
@hron84 Paddies are just blocks, no tile entities involved

Grapes are their own block, `BlockGrapeBlock`

**Comment by ghost** [comment]
@IceDragon200 What about using your pipes system that you created and simply add  another machine that is compatible with golems.

**Comment by IceDragon200** [comment]
@trollworkout Pipes are defunct, and will be a different mod, so maybe in the future

**Comment by Sunconure11** [comment]
For filling paddies, why not allow thaumcraft use golems with a water bucket in hand to fill up paddies?

**Comment by hron84** [comment]
@Sunconure11 <del>because in this case these blocks should be valid tanks.</del> Sorry, early morning. I have a doubt if USE golems can refill it's bucket when got empty. There is no way to detail the steps for the golems, they can use items like saplings that are fully consumed and tools like shears that not consumed until break then fully consumed, but water buckets are an items that replaces itself.

**Comment by ghost** [comment]
@IceDragon200  my best advice would be simply make golems ignore grapes, hops and rice paddies IF possible. 

Based on what was said above you can simply disable bone-meal on grape trunk, rice paddies and hop trunks but keep bone-meal on hop/grape leaves. I think this would disable Golem bonemeal checking logic. I don't know :D I just keep them away from those plants hehe

The lore friendly explanation is golems are not smart enough to figure those out so it requires human touch to those plants. Growthcraft is all about human touch anyway not golems doing your dirty work for you hehehehe

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.

We are looking at implementing this request in newer versions.
