### ISSUE TITLE
GrowthCraft Vehicles & GrowthCraft Animals #Feature Request 

### ISSUE THREAD

**Issue by TheGamerXD** [GrowthcraftCE/Growthcraft-1.7#226]
Allright , so first of all , this is a request . But in my opinion , this is a farm based mod . A farm has vehicles and of course animals. I am going to take the code and try to adapt it for a module that handles cars. Please let me know if it`s worth the time . Also , by cars i mean tractors , combines , trailors , cultivators and more.

**Comment by Sunconure11** [comment]
Please keep major suggestions like this to the forum, this is for bugs mainly.

Also, at least most of what you mentioned is too technologically advanced for this mod.

There might be a few animals sometime in the future, but, only because they fit the theme of a specific module (looking at milk). I'm not going to give any other details.

If however, you really want to do this, look at this page: https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Module-Contribution-Guide

**Comment by HanatakeYurii** [comment]
I'm not really sure Growthcraft goes in pure farm, it's more on fermenting and products made with primary ressources from farming. It's not going in a way like Harvestcraft, Agricraft or Minefactory did (in my mind at least)

**Comment by Alatyami** [comment]
Great idea, but like the others mentioned, it really is out of scope for
Growthcraft. None of the GC items would benefit from a Tracker or
mechanized harvesting. Your ideas would fit better with mods that are
focused on farming. Growthcraft focuses more on the processing of foods
rather than farming them.

We do have some ideas for some new animals but the animal would need to
produce a by product that would be used to make something else.

Alatyami

**Comment by Sunconure11** [comment]
@Alatyami Close this, then?

**Comment by Alatyami** [comment]
Yes. I would do it, but GitFork isn't being friendly.

**Comment by IceDragon200** [comment]
I can't even...

**Comment by Sunconure11** [comment]
Say, can you model a thresher (if you were planning on modelling)? Me and Pitch have plans for a wheat module, we have no tractors or anything like that, but, we have plans for a thresher, on the lines of these:

https://upload.wikimedia.org/wikipedia/commons/6/6b/Batteuse_1881.jpg
http://img1.wikia.nocookie.net/__cb20110328192442/tractors/images/e/e3/Avery_Thresher.jpg
https://www.thehenryford.org/exhibits/pic/1997/cutway.jpg
