### ISSUE TITLE
Brewing inconsistencies, Cauldron Vs Keg

### ISSUE THREAD

**Issue by Midaychi** [GrowthcraftCE/Growthcraft-1.7#236]
More of a question than an issue but is it intentional that recipies involving using yeast and such in the brewing kettle are inconsistent with keg?
As an example, it only takes 3 ethereal yeast per 3 buckets of alcohol in the kegs, but bayanus yeast only processes _40_ millibuckets per yeast.
Considering how the only way to get bayanus yeast is to either farm grapes or bug the culture jar (Start a culture going, then put bayanus yeast in the jar before it finishes, will produce more), better hope you enjoy making a chunk-sized grape farm for 3 bottles of port???
Wine isn't the only one, but they're all kind of ridiculous. Possibility of making 1 yeast do 1 full bucket in the cauldron?

**Comment by Ar97x** [comment]
This should be something configurable. I checked out and there isn't a clear option to change it. @IceDragon200 should take a look at it.

**Comment by Midaychi** [comment]
Yeah you can, but you'd have to dive into to the code to decipher the configs enough to do so.

**Comment by IceDragon200** [comment]
@Midaychi @Ar97x It is configgable, why do you think the all the brewing and fermenting recipes have unreasonable times? :P

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/User-API-(2.5.x)#brewing-recipes
https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/User-API-(2.5.x)#fermenting-recipes

**Comment by PitchBright** [comment]
@Midaychi 

You can adjust the amount of Bayanus Yeast it takes to Ferment wine into Port by changing it in your config file labelled "brewing.json"

``` json
{
  "comment": "",
  "data": [
    {
      "comment": "",
      "item": {
        "comment": "Bayanus Yeast",
        "mod_id": "Growthcraft|Cellar",
        "name": "grc.yeast",
        "amount": 1,
        "meta": 2
      },
      "input_fluid": {
        "comment": "Grape Wine",
        "name": "grc.grapewine1",
        "amount": 40
      },
      "output_fluid": {
        "comment": "Port Wine",
        "name": "grc.grapewine5",
        "amount": 40
      },
      "residue": {
        "pomace": 0.3,
        "comment": "Bone Meal",
        "mod_id": "minecraft",
        "name": "dye",
        "amount": 1,
        "meta": 15
      },
      "time": 20
    }
  ]
}
```

If you would like 1 piece of Bayanus Yeast to convert more than 40mb of Wine&Port… you change the "amount" values in "input_fluid" and "output_fluid" from 40, to whatever you feel would be a good balance for you. You can also adjust the "time" it takes, if you'd like to change that too. Everything is highly customizable! :-)

**Comment by PitchBright** [comment]
To answer your original question… the manufacturing of yeast, is not the same process as the utilization of yeast IRL, so there wouldn't be a 1:1 relationship between the two processes. Don't quote me on that though, I'm not a Yeast scientist.

My limited understanding of yeast is that you can use the small amount, to ferment, and it would work its magic, on an infinite amount of fluid. If realism is what you want, I imagine you would set your fluid amounts, to equal the capacity of the Brew Kettle… so that 1 piece of Yeast does the entire Kettle. And probably the same with the Barrel/Keg too.

Like I say, don't quote me on that.

**Comment by Sunconure11** [comment]
Culturing yeast in a jar such as bayanus is intentional. I requested that a while back as some forms of yeast are hard to obtain in large amounts. And besides, scientists culture lots of microorganisms in liquid media. Plus yeast often goes after fluids like that IRL. How do you think alcohol came along even?

In fact, it was not even known that yeast was a living organism until microscopes came along!

However, if there is an actual bug for an infinite amount of yeast that consumes no fluid, then post the steps to replicate it, so it can be dealt with.

**Comment by Midaychi** [comment]
?
No. In the culture jar, if you start a culture going, you can place any yeast in the output slot and more of that will be produced regardless of biome or whatever. Put Bayanus yeast in culture jar output slot while processing unhopped ale, get more Bayanus yeast.

**Comment by Sunconure11** [comment]
That is intentional, like I said before. Any young fluid can be used for culturing yeast like that.

**Comment by IceDragon200** [comment]
@Midaychi That is the intended behaviour

The Jar follows this procedure:

``` ruby
if jar.is_empty?
  do_nothing
elsif jar.has_young_fluid? and jar.has_yeast?
  duplicate_existing_yeast
elsif jar.has_young_fluid? and not jar.has_yeast?
  randomly_select_available_yeast_and_fill_slot
end
```

IF we didn't duplicate, then the random selection would fail every once in awhile where it selects something different from the existing yeast:

```
> Accepted as first loop > accepted as it's the same as before > not the same > discard and lose work cycle > continue loop
> select BREWERS > select BREWERS > select LAGER > discard LAGER > continue loop
```
