### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#25]
Now that Growthcraft is ran by the community, we at least need a license, [MIT](http://opensource.org/licenses/MIT), [GPL2](http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html), [GPL3](http://www.gnu.org/licenses/gpl-3.0.en.html), [Apache-V2](http://www.apache.org/licenses/LICENSE-2.0), [MMPL](http://bdew.net/minecraft-mod-public-license/) or something else, that way we don't run into the big bad, wild west of copyrights later on.
Also a written claim that Gwafu has passed full control of the project to the community (an email is fine I believe).

Also, I'm no law expert, I'm just doing the usual routine stuff for new projects

And open for discussion, WDYT

**Comment by Alatyami** [comment]
Legally, we are covered as he made the code readily available and full
credit has been given and we are not making any money off this. This is
also the reason why we are maintaining the fork structure.

But you are right. We need to go towards a general open source license to
make sure that those that fork us are also covered.

James E. Hunt

**Comment by spannerman79** [comment]
Perhaps http://creativecommons.org/licenses/by-nc-sa/4.0/ ?

Edit: But to ensure proper licence carry over @Gwafu  must update the [Licence](https://github.com/Gwafu/Growthcraft-1.7/blob/master/LICENSE.txt) too.

**Comment by Alatyami** [comment]
I'd say that one is close ... I think we are looking for a license that is open for modification but others cannot publish their versions of it. Trying to limit future conflicts with other distro's. @Gwafu is listed as a Collaborator on our repo's so that when/if he does come back he still has control over what we have and distribute.

**Comment by spannerman79** [comment]
> I think we are looking for a license that is open for modification but others cannot publish their versions of it

In that case http://creativecommons.org/licenses/by-nc-nd/4.0/

> @Gwafu is listed as a Collaborator on our repo's so that when/if he does come back he still has control over what we have and distribute.

Still ... for "legal" terms @Gwafu still must update his Licence to reflect his acceptance that anyone can create work based on his code - and that Licence must be located within the repo - or code base - for all to see.  Otherwise http://creativecommons.org/licenses/by-nc-nd/4.0/ will be null and void.

**Comment by IceDragon200** [comment]
Well, we have a license (me thinks)
