### ISSUE TITLE
AppleCore API

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#26]
Can you guys make Growthcraft implement/compatible with the AppleCore API? 
That'll make it work with Hunger Overhaul and Spice of Life, I believe.

**Comment by IceDragon200** [comment]
@PitchBright I just read the AppleCore API and checked the Growthcraft code, all items already `extend ItemFood`, and use the `FoodStats#func_151686_a` function, so it should work with AppleCore.

The only issue right now is the custom plant blocks (grapes, hops, rice) since they use custom logic.
I'll try implementing this later today (don't hold your breath though)

**Comment by PitchBright** [comment]
Sorry, you're right, I wasn't even thinking about the food stuff. It was actually those custom blocks I was hoping you could work your magic on.

**Comment by IceDragon200** [comment]
@PitchBright you can check out the PR, I'll put up a link to the jar so you can test it

aka. Be my ~~loyal guinea pig~~ tester :D

**Comment by PitchBright** [comment]
Aight cool. Happy to help. What version of Forge is it built on? I'm running v1291.

**Comment by Ar97x** [comment]
The most recent one I've tested is v1489, but I think it is compatible to most new versions

**Comment by IceDragon200** [comment]
@PitchBright Its built on `1448`, _me looks at the build.gradle again_ yup

**Comment by PitchBright** [comment]
Might be able to close this as per #29 & #27

**Comment by Sunconure11** [comment]
It has been implemented.
