### ISSUE TITLE
Bee boxes spread flowers to tilled farmland

### ISSUE THREAD

**Issue by esotericist** [GrowthcraftCE/Growthcraft-1.7#260]
We're running the growthcraftCE preview build, 5e975d1, and I'm finding that a bee box placed too close to tilled farmland with nothing already on it will happily place flowers on the tilled farmland.

**Comment by IceDragon200** [comment]
@esotericist That's perfectly legal behaviour, try grabbing a flower and planting it on farmland yourself:
**Screenshots**
[Daisies](https://dl.dropboxusercontent.com/u/72618186/screenshots/minecraft/growthcraft/playtest/2016-03-16_09.12.27.png)
[Roses](https://dl.dropboxusercontent.com/u/72618186/screenshots/minecraft/growthcraft/playtest/2016-03-16_09.12.40.png)

Now, if the bee box was placing flowers on stone, you'd have a problem :fearful:

**Comment by esotericist** [comment]
Placing it is one thing, but you can't bonemeal tilled farmland to produce flowers the way you can grass. Even if you bonemeal grass adjacent to farmland, the flowers will not appear there, only on other grass blocks. That's why it seems strange to me that bees would do so.

**Comment by Alatyami** [comment]
Because this is natural behavior we are going to leave it, as is. Just because you cannot use bonemeal on farmland to make flowers does not justify use removing the ability for bees to plant flowers there, you can plant flowers on farmland. Which is natural and flowers can sprout on farmland in real life.
