### ISSUE TITLE
[BUG] [2.5.0] Port wine does not brew

### ISSUE THREAD

**Issue by hron84** [GrowthcraftCE/Growthcraft-1.7#265]
I tried to put Bayanus Yeast and some fresh (young) wine to a kettle, but Port wine does not brew. Is there any additional step to work, because the Wiki does not clear in this topic. Bayanus Yeast also not apply for fermenting barrels (fermentation process does not start).

Version: Growthcraft 2.5.0 1ae3bd2

**Comment by Sunconure11** [comment]
Put fermented grape wine in a kettle, not young wine. And please keep questions like this to the forums.

**Comment by hron84** [comment]
@Sunconure11 can you make the wiki more specific in this case?

**Comment by Sunconure11** [comment]
Follow any instructions laid out on this spreadsheet.

https://docs.google.com/spreadsheets/d/1ykz1iqWUkarnZC76FGyjKs2wExdOgLJ7XHt3haNOV30/edit#gid=1739283064

**Comment by marcoasfonseca** [comment]
I think that would be awesome if you add a "recipe book" to the game, in that book had the recipes to the kettle, fruit press, fermentation barrel, and to the new devices used in butter/cheese, and you had a short description about that wine/Cheese, for example: This wine is original from "Germany", bla...bla
This just because culture is wonderful. Think about it :)

**Comment by hron84** [comment]
I like the recipe book idea.

**Comment by Ar97x** [comment]
It's already in our plans, add books to every module.

**Comment by Sunconure11** [comment]
Can we close this?

**Comment by hron84** [comment]
Yeah, we can. Now I had a time for get a few bottles of port wine.
