### ISSUE TITLE
[CELLAR] [2.5.0] Thaumcraft Magical Forest is not counted as magical biome

### ISSUE THREAD

**Issue by hron84** [GrowthcraftCE/Growthcraft-1.7#274]
The Culture jar creates a normal Brewer's yeast in TC magical forest. If I remember correctly, TC biome should be marked as MAGICAL so the jar should yield ethereal yeast. I think I did everything right.

Please, add the Magical Forest to the Ethereal Yeast biome list.

Growthcraft 2.5.0  60880a1

**Comment by Ar97x** [comment]
Brewers Yeast has a chance to be the output of every biome, including the
ones that have chance to output a specific kind. Remove it from the jar
output slot and let the process happen again.

**Comment by IceDragon200** [comment]
@hron84 Marking a biome is not our duty, mod developers are the ones that mark their biome by type.
If TC's biome was not marked as `MAGICAL` then :scream: 

Side note, if biome types overlap, then the jar will randomly produce one from the available list
Say MAGICAL and MUSHROOM, you may get Ethereal or Origin, due to the sheer number of biome types, you have a lower chance of getting one of the specialized yeast types and a higher chance of just getting brewers yeast. It comes down to chance.
I could add generation weights in the future to help curve this problem

**Comment by IceDragon200** [comment]
@hron84 Poke, any word on this issue? Oh side note I added weights to the yeast items now

**Comment by hron84** [comment]
I finally managed to get an ethereal yeast in Magical forest, but a bunch of brewer yeast yielded before. It was kind of PITA to get a right one, especially because the Magical Forest is quite far from my base and I could not setup any brewing production there.

Also: I'd really appreaciate a lock on the culturing jars that prevents the last yeast to pulled out.
