### ISSUE TITLE
Crash at initializing with v2.5.2

### ISSUE THREAD

**Issue by xJon** [GrowthcraftCE/Growthcraft-1.7#321]
http://pastebin.com/8P9wXb18
Any idea what went wrong?

**Comment by IceDragon200** [comment]
@xJon https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/FAQ---Troubleshooting#illegalstateexception

remove your existing growthcraft json configs

**Comment by xJon** [comment]
@IceDragon200 Very impressive FAQ, thank you.

**Comment by xJon** [comment]
It literally happens to every user after the update to v2.5.2. Is there a better fix?
As a modpack author, it's a bit problematic to tell 10,000 players to delete a specific file in the configs folder.

**Comment by IceDragon200** [comment]
@xJon: Nope, this was a issue present during development, and it only happens because users upgraded from 2.4.x, I've tried to catch the GSON error and print to the console, but it just falls right through the error handling.

Would you prefer if I just silently deleted everyone's config files?

**Comment by xJon** [comment]
@IceDragon200 Can't you only delete the .json config files? Sure there isn't any other way than deleting everything?

**Comment by Sunconure11** [comment]
Yes, that is what you are supposed to do.

**Comment by xJon** [comment]
@Sunconure11 As you can see from the other messages, I meant that the mod would do it automatically, instead that all the users will do it manually, as it very problematic with modpacks.

**Comment by IceDragon200** [comment]
@xJon 

## Modpacks

Since you're running a modpack, you **SHOULD** be including the growthcraft json configs, not relying on us to update them. These configs **MUST** be in sync with the server and client to work correctly, otherwise you'll encounter undefined behaviour.

## When updating

Even more so, you should be paying attention to the mods you update especially when they aren't updating in a `teeny` or `patch` level version (x.y.Z where Z is the tiny eg. from 2.5.1 to 2.5.2).
Growthcraft uses semantic versions, so if we update a minor version it means **something critical changed and you SHOULD check your configs** as we most likely added some breaking changes.
I'm saying this from experience, haphazardly updating mods, packages, or applications is a royal way to screw yourself over.
I'm assuming you already do this, but ALWAYS test before pushing upstream, or deploying.

## Only affects users upgrading from 2.4.x to 2.5.x

Once again, the json config errors are caused by users updating from 2.4.x  to 2.5.x, and you won't experience it if you updated within the 2.5.x series.

## We will not modify, AND OR remove already present config files

Once the configs are generated the first time, Growthcraft **WILL NOT** modify them: as modifying these files after creation can potentially remove user settings (dropping whole recipes from the config), AND OR add unwanted behaviour (re-adding recipes that where removed, or modified to fit the user).

## References

Semantic versioning

> X.Y.Z
> X = Major Version, we've updated to a new version of Minecraft (definitely something broke)
> Y = Minor Version, we've added new features to the existing
> Z = Teeny Version, we've fixed several minor issues, or including some small non-breaking changes

I'll be adding this to the wiki on the FAQ.

**Comment by xJon** [comment]
So you're saying I should include the full configs with the modpack, and refresh them after every Growthcraft update?

**Comment by Sunconure11** [comment]
Refresh them every time a major config addition is done.

Same with User API changes.

**Comment by xJon** [comment]
Maybe you can just note that in the changelog. Thanks anyway, I got my answer!

**Comment by xJon** [comment]
Should the configs also be refreshed with server packages?

**Comment by IceDragon200** [comment]
@xJon Client and Server configs should be the same, so yes :)

**Comment by xJon** [comment]
@IceDragon200 But does it make sense that servers don't crash in the update?
