### ISSUE TITLE
Ricotta curds give just one bowl, is that intended?

### ISSUE THREAD

**Issue by cheesealmighty** [GrowthcraftCE/Growthcraft-1.7#326]
Oh god I feel like I'm spewing one issue after another, sorry if I'm being a bother :3 

Anyway, since a wheel of cheese seems to be producing 64 slices, making a whole bag of ricotta, then see it turn into one measly bowl of cheese a bit, umm, discouraging (however much your love for ricotta might be). So, would you consider to increase the output to 64 or maybe 32, since it's a byproduct of cheese production?

**Comment by IceDragon200** [comment]
um... :scream: @PitchBright @Sunconure11 SAVE US, What should we do about this?

**Comment by Sunconure11** [comment]
Config option to allow for more ricotta, default setting is maybe 4 bowls, but it can go as high or as low as the game can support.

**Comment by IceDragon200** [comment]
@Sunconure11, @cheesealmighty New dev build contains the config option (growthcraft/milk.conf) "Ricotta Bowl Count" it defaults to 4, please only use values between 1 and 8 (I forgot to write it in the config)

**Comment by Ar97x** [comment]
Since we're talking about the quantity of cheese, I really don't like
having to eat 1 slice per hunger bar. I think that 64 hunger bars per
cheese block is a good amount, because we've a lot of work to get all of
the materials, but I would like them to be better distributed, or at least
a config option to do it. I think 16 slices per block, each slice giving 4
hunger bars is a good value (or 32 - 2).

**Comment by PitchBright** [comment]
@cheesealmighty 
Dragon and I discussed it tonight. The summary of our conversation is… Ricotta is a very very low yield cheese, made from the cheese-making byproduct whey. It's not meant to yield very much. If you want to change the recipe and the yield, you should use a mod like MineTweaker to change it.

@Ar97x 
Cheese typically isn't a food you eat for nutrition, or because you're hungry. It's widely considered a luxury food. We didn't add cheese to GrowthCraft to make it a staple food. Its current hunger values of 1 bar per piece are appropriate for what cheese is… "a tasty snack". If you want high nutrition and saturation food… that's what meat and potatoes are for. If you want custom hunger values for your food items, you should use a mod like HungerOverhaul to change them.

**Comment by cheesealmighty** [comment]
@PitchBright 
Yeah, I knooow. Something like 4-5 liters of whey amounts to what, a bowl of ricotta or something. Eh, in any case, it's fine as it is and I'd rather not change overall balance of the mod. :3

**Comment by Sunconure11** [comment]
@cheesealmighty Shouldn't you close this now that it has been resolved?

**Comment by cheesealmighty** [comment]
@Sunconure11 Yup, wasn't sure if I was allowed to do stuff :3 _notes to self_
