### ISSUE TITLE
Redstone activation for cheese press

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#328]
I had some issues with activating the Cheese press while working on the wiki info. Most times right clicking would return the cheese stored in the press. If we can redstone activate it, it would help with applying the press and automation.

**Comment by cheesealmighty** [comment]
If you have a empty hand, you put the cheese in and out. If you have something in your hand, you activate/deactivate the cheese press. I'd rather not have to stick a lever in there again. Hell, I would rather have the same design for the fruit press.

**Comment by cheesealmighty** [comment]
Isn't it so that when you right click it with your empty hand, you get cheese in and out and when you click with any item, it activates and deactivates the press? To be honest, I'd rather not have a lever stuck in there to use it. 

I guess while we're at it, I'd rather have the same system for the fruit press. Because, umm, the lever looks hideous :3

**Comment by IceDragon200** [comment]
@Alatyami @cheesealmighty Latest development build 5d14150 has this

**Comment by cheesealmighty** [comment]
@IceDragon200 ooops, sorry then.
