### ISSUE TITLE
Creating Mead Must Bucket consumes bottles

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.7#347]
The Mead Must Bucket shapeless recipe returns the bucket (with mead must) but destroys the bottles from the water - I expected bottles to be returned.

**Comment by IceDragon200** [comment]
@Syndaryl NO BOTTLES 4 YOU. Did you check your inventory, they where probably returned there (if you had no space on your hotbar) or they where ejected into the world

**Comment by Ar97x** [comment]
I don't think so. I think I've experienced the same bug.

**Comment by IceDragon200** [comment]
@Ar97x @Syndaryl Minecraft doesn't register the water bottle with a container item, the recipe handler would normally refund you the container item, but since water bottles don't have one, you get nothing in return.

I'll write a new handler specifically for this:
Change of plans, I can't do anything about it, it's handled by minecraft's SlotCrafting class

**Comment by Syndaryl** [comment]
Minetweaker lets you refund any random item you want out of a specific recipe. Might be worth looking into what they're up to.

**Comment by SimonMeskens** [comment]
I added configs for this in the dev branch. They allow you to make vanilla water bottles act more like GrowthCraft water bottles. The water bottles being consumed is a vanilla feature, where buckets last, bottles break on use. The config will allow you to change both capacity and if they return empty bottles.

Should be in the next dev release at #307

**Comment by ghost** [comment]
Water bottles in forge 1.7.10 is a pain in the butt.  I 've seen the struggles all over.
