### ISSUE TITLE
Please Help! Collecting Etherial yeast!

### ISSUE THREAD

**Issue by lShanghaiMoonl** [GrowthcraftCE/Growthcraft-1.7#409]
This has been a frustration of mine for quite some time I have searched the internet far and wide  with with no **avail**; In what way am I to obtain **ethereal yeast**? I know it say its in a"**magical biome**" but that is extremely broad. Does that mean **Thuamcraft's** magical forest biome? If so would I have to start a farm in this magical forest? If it is not **Thaumcraft's** magical forest biome, then what is it something vanilla like the **Nether**? Please help the community and inform us **exactly** on how to obtain this yeast. 

Thanks.

**Comment by Ar97x** [comment]
The "Magical Biome" means that every biome tagged as "Magical" should work,
so yes, Thaumcraft Magical Forest and other biomes from Biomes O' Plenty
and etc will work. Also, you can configure the config files for new tags, I
configured mine to work on The End, and the Origin yeast to the Nether,
because I have no magical biomes on my modpack. If you're interested I can
upload it and send you a link.

**Comment by lShanghaiMoonl** [comment]
Thank you for shedding some much needed light on this. Okay, what are the chances that this yeast will drop in a magical biome because when I went into the configs and only saw the chances for Bayanus yeast. Additionally, aside from **Thaumcraft** and **Biomes O' Plenty**, what else has been tagged as **magical** for vanilla and non vanilla? I would appreciate if you could **give me an example** of how I can find the parameters to change these tags? Also to create new ones as well? As I am going to add them for **Abyssalcraft** biomes the **Aether** and **Twilight Forest** (If they aren't already) here is what im looking at in the configs... is this the right directory? 

**Configs/growthcraft/cellar/yeast.json.default**

In the configs this is what im looking at.....
{
      "comment": "Ethereal yeast is found in MAGICAL biomes, because its special",
      "item": {
        "ore": null,
        "comment": "Origin Yeast",
        "mod_id": "Growthcraft|Cellar",
        "name": "grc.yeast",
        "amount": 1,
        "meta": 3
      },
      "weight": 10,
      "biome_types": [
        "MAGICAL"
      ],
      "biome_names": []    **<-------- Do I put biome names in the brackets??**
    },

**Comment by IceDragon200** [comment]
@lShanghaiMoonl if you know the registered name of the biome you can put it in the biome_names, otherwise you specify by type

**Comment by lShanghaiMoonl** [comment]
How does one Find the registered name of a biome if you do not know it? @IceDragon200

**Comment by IceDragon200** [comment]
@lShanghaiMoonl F3, minecraft shows the name of the current biome you're standing in, if your lucky you can find the biome in question and get it's name.
Otherwise, I could write up a utility to dump the names of all the registered biomes

**Comment by lShanghaiMoonl** [comment]
okay @IceDragon200 i tried to input a few biomes into the Biome_names area with these parameters
["Example Biome" ,] but when i did that i couldn't even launch my server it just kept rebooting until I reverted it back to the original .json what could be going wrong?

**Comment by IceDragon200** [comment]
@lShanghaiMoonl http://jsonlint.com/, copy the contents of the file into that and check it for errors.
Don't leave trailing commas in the array or at the last element in the object

// BAD

``` json
{
  "object": {
    "key1": 0,
    "key2": 1,
  },
  "biome_names": ["Example Biome", ],
}
```

// GOOD

``` json
{
  "object": {
    "key1": 0,
    "key2": 1
  },
  "biome_names": ["Example Biome"]
}
```

Also, why not copy the actual error log instead of saying your server didn't even launch (anything could have happened you know, like Java decided to update, your graphics drivers died somehow), error log next time.

Also please, PLEASE don't post the error log directly here, put it on http://gist.github.com/, you get it for free with your github account, link the new post here and I'll check it

EDIT:
The latest build now includes the Biome dumper, it dumps the biome id, name and types so you can pick from the list :)

**Comment by lShanghaiMoonl** [comment]
@IceDragon200  We Really appreciate the support and help you have supplied me with. We are starting a Modpack for ATlauncher and need your permission to use this mod in it. Is that okay?

**Comment by IceDragon200** [comment]
@lShanghaiMoonl Open another issue here with the modpack name and mod list, I'll approve it and add it to our list :)

**Comment by lShanghaiMoonl** [comment]
Okay there are a lot of mods like 80+it may take us a minute @IceDragon200, but we will do it because no modpack is complete without growthcraft! :)
