### ISSUE TITLE
Massive feature request

### ISSUE THREAD

**Issue by Indevious** [GrowthcraftCE/Growthcraft-1.7#428]
Thought about just dumping a list of ideas I've had for a while now.
More than just jerky, dried meats, salami and prosciutto and the like
Some cooking like Apple milk tea but less confusing
Vodka and perhaps absinthe and rum too
Vinegar and pickling
More plants
Just wanted to jot these down and get them out there, sorry if some have been posted before!

**Comment by vrnRaptor** [comment]
I will add. I would like to see in-game tutorial book.

**Comment by IceDragon200** [comment]
@Indevious Sorry, late reply, maybe you can pitch these ideas for:

https://github.com/GrowthcraftCE/Growthcraft-1.10
https://github.com/GrowthcraftCE/Growthcraft-1.11
https://github.com/GrowthcraftCE/Growthcraft-1.12

Since we don't really have meats in Growthcraft, we've have to park the dried meat idea for a bit, unless we add Growthcraft Meats

We had cooking planned, not sure what happened to that idea, I was working on a hot plate block.

Vinegar and pickling, AHA, a use for vinegar!
But I don't think we have any vegetables...

More plants indeed, we'd need vegetables for the vinegar, maybe we could pair up with AgriCraft for that.
