### ISSUE TITLE
Fishtrap: Item's not being pulled and loot is OP

### ISSUE THREAD

**Issue by AlexHeaps** [GrowthcraftCE/Growthcraft-1.7#431]
Hi there,

Having a couple of issues with the Fishtrap.
1) No items are being pulled from it. If I attach an item which should pull (Extra utilities transfer node/Minecraft Hopper, etc), the items aren't moving from the fishtrap.

2) Loot I get from the fish trap is incredibly overpowered, despite config change. I'm getting diamonds/ingots, etc, instead of fish.

Will attach modlist + configs tomorrow, as it's quite late.

**Comment by IceDragon200** [comment]
Fishtrap was never meant for a hopper, since it was placed in the water, ~~I believe it outputs from the side.~~ It had no output whatsoever.

Yes, I'm aware the drops are OP (it was mentioned on the forums), if you don't want the iron ingots, etc. Edit the following config file:

`$MINECRAFT/config/growthcraft/fishtrap/catch_groups.json`

<details>
<summary>JSON</summary>

```json
{
  "comment": "",
  "data": {
    "legendary": {
      "comment": "Stuff you probably would never find on average",
      "weight": 10
    },
    "fish": {
      "comment": "Fishes",
      "weight": 1
    },
    "junk": {
      "comment": "Useless Stuff",
      "weight": 3
    },
    "treasure": {
      "comment": "Fancy Stuff",
      "weight": 5
    },
    "mineral": {
      "comment": "Ingots and other metallic stuff",
      "weight": 7
    }
  }
}
```
</details>


**Remove the mineral section like so:**
<details>
<summary>Updated JSON</summary>

```json
{
  "comment": "",
  "data": {
    "legendary": {
      "comment": "Stuff you probably would never find on average",
      "weight": 10
    },
    "fish": {
      "comment": "Fishes",
      "weight": 1
    },
    "junk": {
      "comment": "Useless Stuff",
      "weight": 3
    },
    "treasure": {
      "comment": "Fancy Stuff",
      "weight": 5
    }
  }
}
```
</details>

That will remove ingots and the like from the fishtrap.

You can also edit the loot in question by editing `$MINECRAFT/config/growthcraft/fishtrap/entries.json`

Please give the latest build in #430 a test (it should allow hoppers to take items from fishtraps now)

**Comment by hron84** [comment]
Fish trap also does not produce harvestcraft fishes. It would be wonderful if you can take an account for them.

Do you have a plan when 2.7.2 will be available on Curse?

**Comment by IceDragon200** [comment]
@hron84 You should open a new issue if requesting compatibility.

2.7.2 will be released (eventually? I need to ping Alatyami about that)

**Comment by Alatyami** [comment]
Ping received .... publishing now.

**Comment by draknyte1** [comment]
Pulling items from Fishtraps has always worked for me since pre-community.
EnderIO item conduits handle it fine.

**Comment by moxventura** [comment]
Drops being OP looks like a bug. I think the WeightedRandom function was misunderstood. A higher number means more chance of the item being returned.
Edit `$MINECRAFT/config/growthcraft/fishtrap/catch_groups.json` as followed to fix:
```json
{
  "comment": "",
  "data": {
    "legendary": {
      "comment": "Stuff you probably would never find on average",
      "weight": 1
    },
    "fish": {
      "comment": "Fishes",
      "weight": 20
    },
    "junk": {
      "comment": "Useless Stuff",
      "weight": 7
    },
    "treasure": {
      "comment": "Fancy Stuff",
      "weight": 2
    },
    "mineral": {
      "comment": "Ingots and other metallic stuff",
      "weight": 3
    }
  }
}
```
