### ISSUE TITLE
Thistle not working for rennet any more

### ISSUE THREAD

**Issue by f0kx** [GrowthcraftCE/Growthcraft-1.7#432]
After the update, god knows what was the changelog (can't find it) i cannot use thistle in  Brew Kettle any more pls help or do you implement a new mechanic for it?

**Comment by IceDragon200** [comment]
Have you tried throwing out your existing brew kettle recipes ($MINECRAFT/config/growthcraft/cellar/brewing.json), and trying it again?

**Comment by f0kx** [comment]
you mean delete it and let it create it again after restart?  no will try it ! and btw can you say what you have changed in the newer version of growthcraft

**Comment by f0kx** [comment]
okay it works !! thx but should i delete all file after updating ?

**Comment by IceDragon200** [comment]
@SugarDaddii Sometimes you'll need to delete the configs due to changes.

As for the changelog, if you don't find it on our releases section you can always review the PRs

**2.7.2**
https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/430

**2.7.1**
https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/424
