### ISSUE TITLE
( BUG ) GUI 

### ISSUE THREAD

**Issue by carlindoplay** [GrowthcraftCE/Growthcraft-1.7#436]
Hi, I'm from Brazil, I'm having problems with the GUI when I open it and the layout gets darkened (please help me) http://prntscr.com/e9o5a9 http://prntscr.com/e9o5f9 http://prntscr.com/e9o5qg

ola eu sou do brasil , estou tendo problemas com o GUI ao abrir e layout fica escurecido ( por favor me ajude ) http://prntscr.com/e9o5a9 http://prntscr.com/e9o5f9 http://prntscr.com/e9o5qg

**Comment by Alatyami** [comment]
We havent seen that issue before. And can you send us your mod list with versions included. It easiest would be to provide your startup log as it will point out any conflicts that might be occurring.

**Comment by carlindoplay** [comment]
This is my modpack http://prnt.sc/e9ocu4

**Comment by carlindoplay** [comment]
I'm using forge 10.13.4.1558

**Comment by Alatyami** [comment]
Hrm ... All of those mods look OK. Are there any exceptions that show up in the logs?

**Comment by carlindoplay** [comment]
I do not know where I can see this.

**Comment by carlindoplay** [comment]
Should be it http://prntscr.com/e9pwsk

**Comment by IceDragon200** [comment]
@carlindoplay You could try rebuilding your modpack by adding Growthcraft first, and then any known to work mods (buildcraft, Thermal Expansion, Thaumcraft, etc...)

Then slowly add other mods until the GUI issue happens.

You could add the mods in batches until it breaks and then remove them until the issue goes away.

Once you target the problem mod (or mods), you can then place Growthcraft and the problem mods into a context/pack by themselves to see if the issue is with the specific mods, or with something along with them.

But judging from your screenshots it seems like a lighting issue (something could be toggling GL lighting and not resetting it correctly, could be us...)

**Comment by carlindoplay** [comment]
Ok I'll do it, I hope it solves the problem.  
..thank you for your support

**Comment by carlindoplay** [comment]
I put only 1 mod and the problem persists, it could be my computer or java problems  http://prnt.sc/ea14hg http://prntscr.com/ea16ij

**Comment by IceDragon200** [comment]
Can you grab your forge logs and upload them on gist for us to look at. If it's a GL problem it's usually logged.

Also, OS version, Java version, and GPU (if any), if you have a multiple GPU system try using different ones.

I'm curious: what is that fourth item?

**Comment by carlindoplay** [comment]
Log https://paste.ee/p/i8kYP
My operating system http://prntscr.com/ea3s3r 
Java version http://prntscr.com/ea3t4z
log  https://paste.ee/p/69DYK

**Comment by carlindoplay** [comment]
With the logs is it possible to find out the GUI problem?

**Comment by IceDragon200** [comment]
@carlindoplay Seeing as this problem only occurs with your computer it's harder to debug.

I'm suspecting it's something GPU related, if you have anyone with a different computer you could try the mod's there.

Also, could you try changing your minecraft graphics settings (try changing between fast graphics for example).

**Comment by carlindoplay** [comment]
Okay, I'm going to test the mod on another computer if the problem is my computer I will formatare for windows 64 bit
Maybe the mod works fine with java 64 bit
