### ISSUE TITLE
NEI support request, or permission for someone else to do it

### ISSUE THREAD

**Issue by enarkay** [GrowthcraftCE/Growthcraft-1.7#441]
My main desire and request here is that I want NEI support for the special recipes of the mod, like products processed through special machines/tools and not just the recipes from the normal crafting bench.

Now I've seen some related requests and answers on the github issue page, but my main concern is that since you seem to be planning for a 1.10 update, my guess is that you will be busy preparing for the version update and it's unlikely to see such feature update for 1.7.10. Correct me if I'm wrong though, in which case I will be absolutely grateful :)

So here are my requests/questions
**1)** Can and will you implement such feature for 1.7.10 version of the mod?

**2)** If the above is unlikely just as I fear, may I have your permission to find or hire a modder who is capable and willing to do the job? I've actually already done something like this before, and the modder didn't actually make changes to the mod itself but made a custom version of NEI_Integration mod to access and view the special recipes of the mod. So the two sub questions I would like to ask then are:
**2-a)** Is it okay for another modder to make changes to the mod itself?
**2-b)** Is it okay for another modder to make a custom version of NEI_Integration to access and view the special recipes of the mod?

**Comment by IceDragon200** [comment]
__tl;dr__

We welcome anyone who wishes to add the NEI integration, also any new developers who are willing to join the ~~sweat shop~~ development team.

I believe the 1.10 port is being headed by @SirWindfield

__Longer Version__

Hmm, you don't have to ask permission to do an integration/feature: "Just Do It" ~ Shia Labeouf 

If anyone is willing to take up the 1.7.10 torch, they can post an issue here stating their wish to take over the mod, we'll add them as a collaborator and give them push access.

Otherwise users are free to fork the project to add features and open a PR here, I'll review it when I'm free and merge it in, @Alatyami will handle new releases, or you can just build it locally and use a dev build.

I think there is a fear of the development team, that we chew up anyone who tries to come near the project. (okay it's kinda true, if they try to do something utterly stupid with it, we'll chew em up)

I'd like to say, there is no need to fear us, I'm all for new developers coming on board and adding new features to the project.

I just expect a certain code style (Allman), that's about it.

**Comment by mainrs** [comment]
@IceDragon200 Ye I do, though that I currently have exams to write and literally no time to code anything 👎 I ported 4 modules to 1.10.2 and added some stuff to them. Hopefully I'll have more time in July/August to port the rest.

**Comment by chaos234** [comment]
I am not sure why but I found this while searching for NEI in this repro: https://github.com/GrowthcraftCE/Growthcraft-1.7/tree/beea035d0cb0041b5fc3b1f153bb7b9e665dc218/src/java/growthcraft/cellar/integration/nei

I am confused while they are there but not in one of the branches yet so maybe moving them to the current 1.7.10 branch (developmen) should be fine since I also could not find the added option for it or am I missing smth. ?

But it seems to be disabled for what ever reason so in no config the NEI-Module seems to be available but maybe by adding it manually?

Found this one while searching: https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/beea035d0cb0041b5fc3b1f153bb7b9e665dc218/src/java/growthcraft/core/GrcCoreConfig.java#L45-L46

Deeper Research ended up in this search results where all NEI support via module was commented out but why?

https://github.com/GrowthcraftCE/Growthcraft-1.7/search?utf8=%E2%9C%93&q=enableNEIIntegration&type=

Much more questionable is this change: https://github.com/GrowthcraftCE/Growthcraft-1.7/commit/88d662933fb2471f730932ab665a81da389579a9#diff-5e1a64eae2042141cc60892b2c1d4060 which disables all NEI Handlers for the cellar and so on. So there was a NEI support but for what ever reason it was disabled.

So I'll checkout what is going on there and if all is fine with it, I'll send a PR back to the development repro. But I think there was a reason why @IceDragon200 had removed it so maybe he can answere this?

**Comment by enarkay** [comment]
@chaos234 Hey that's a great find! :) I've actually just given up until now, since I could not find any developer who's willing to do the job. Yeah I'd also like to know why it was disabled somewhere on the way. And if there is indeed a way to add back the handler support for the mod, that would be great!

**Comment by IceDragon200** [comment]
@chaos234, @enarkay  It's been awhile, but going by my usual mental pattern, the code likely didn't work as expected and was causing more trouble than it fixed, you can uncomment the line and compile it locally to find out if it is working though

Just read the commit you linked: yep it was likely causing trouble which is why it got disabled

**Comment by chaos234** [comment]
Alright @IceDragon200 - I'll see what it will cause and I'll try to fix it :) - Would be maybe a bit of debugging but this shouldn't be that problem :).

Edit: For what ever reason "src/java/growthcraft/api" was marked as source path in my environment which has caused problems. Resolved by removing this folder from the sources list.

**Comment by chaos234** [comment]
@IceDragon200 - what has gone wrong with my setup?

![](https://puu.sh/xSCiu.png)

I am not sure why but maybe I did something wrong or maybe other things are broken?

Log: https://hastebin.com/tuquboresi.md

EDIT: Added them as ressourcepack in my dev-environment and after enabeling NEI aggain I see what is going wrong so time to try to fix this :)

**Comment by IceDragon200** [comment]
Seems the textures are missing, dunno why though o_e

Did you run `gradlew run` I forgot what the command was to run the test client

**Comment by chaos234** [comment]
I have added them over an ressourcepack manually for the testing environment.

What I currently try is to create "getAllRecipes" because it seems to be missing or I oversee smth. because to access not only "n" recipes of one input/output (fluids are not be able to reference to any processing machine, whyever) since you can normaly access all recipes of this machine when applied.

For this an TransferRect is needed and also applied but it has no response even if it's showing "Recipes" so more research todo I think so it will take a while ^^.

Oh and why are in the lookup from the fermentation recipes sometimes empty ones? Normaly there should be a few more since u can use a netherwart, glowstone dust and/or redstone so I assume that smth. is going wrong there ^^.

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.
