### ISSUE TITLE
Fishtrap and Harvestcraft [1.11]

### ISSUE THREAD

**Issue by Kisutora** [GrowthcraftCE/Growthcraft-1.7#443]
As Growthcraft 1.11 Alpha 3.0.0.1 came out I decided to leave a few fishtraps underwater while I went to have some breakfast and when I got back to it these were the results: ![sample 1](https://user-images.githubusercontent.com/22685232/28403781-f5c9db9e-6d2e-11e7-9116-1e93852d4e81.png)
![sample 2](https://user-images.githubusercontent.com/22685232/28403782-f5ca7950-6d2e-11e7-94d4-6127ee5b376e.png)
 As you can see with Harvestcraft installed the Fishtraps fill up very quickly if you're going the manual route. This overflow of fish can be dealt with by building an automatic hopper chest system![automatic farm](https://user-images.githubusercontent.com/22685232/28403779-f5c822fe-6d2e-11e7-9318-a63c2c93efd9.png) so I thought I'd just let you know that this is a thing and it could possibly be annoying for players that don't want an automatic fish farm and have Harvestcraft installed. For me however and probably for most players you'll be building an automatic farm anyways so I don't see this as a problem. **What is a problem however is Harvestcraft fish going into the item slot reserved for rotten flesh.** Thanks!

P.S. The fishtrap appears transparent when you hold the block in your hand but when you place it it's not transparent.
![fishtrap transparency](https://user-images.githubusercontent.com/22685232/28403778-f5c814b2-6d2e-11e7-83bd-c6f0e8ce2627.png)
![manual farm](https://user-images.githubusercontent.com/22685232/28403780-f5c9686c-6d2e-11e7-96c1-262bf7486b34.png)

**Comment by Alatyami** [comment]
Are you able to report issues via the Growthcraft 1.11 repo? https://github.com/GrowthcraftCE/Growthcraft-1.11/issues

The bait issue is known, that is the last major item to finish. 

Transparency when placed in the world ... when the texture render the back doesn't render and it looks bad. this was also the case with 1.7

The overflow, is an interesting observation. The new Fishtrap actually acts more like a hopper. If you do not add the hoppers it will fill the inventory slots up to "6" anything beyond that will be ditched. Because you added hoppers, it looks like it gives the overflow somewhere to go. That is not intended behavior.  The LootTable is built from the same loot table as the Fishing Rod, so getting the Harvestcraft fish makes sense and would be intended. In the future, we'll add a filter mechanism via a config file.

I have plans on having the Fishtrap, Gold Fishtrap, and Diamond Fishtrap with additional inventory slots. But that would be for 3.1.0. Currently the plan is to port everything over and then add features.

**Comment by Kisutora** [comment]
Great! Glad I could be of any help. I'll post this over to the right place now ;)
