### ISSUE TITLE
 How to get a hyper-extended effect

### ISSUE THREAD

**Issue by miciek2** [GrowthcraftCE/Growthcraft-1.7#454]
Hey. I have problem with getting hyper-extended effect pls help. (google translate)

**Comment by IceDragon200** [comment]
@miciek2 Ferment any `FERMENTED` Booze using `Redstone Dust` in a `Fermentation Barrel`

**Comment by miciek2** [comment]
@IceDragon200 fermentation barrel + redstone dust + fermented Sake/grape itp = Grape fermented extended ;x 
Could you record a movie how to do this one Hyper-Extended effect? (google translate)

**Comment by IceDragon200** [comment]
@miciek2 ~~Extended is Hyper-Extended I just shortened it for the tag~~

Scrap that, I think I screwed up something

Okay I got it now, not all booze has a hyper extended state, some have special states obtained by using ethereal yeast.

Ferment using Ethereal Yeast to obtain the hyper extended

__tl;dr__ Ferment any `POTENT` or `EXTENDED` Booze using `Ethereal Yeast` in a `Fermentation Barrel`

Sorry about the trouble, it's been awhile since I've looked through the code, probably need to have an updated guide

**Comment by miciek2** [comment]
@IceDragon200 How to get Ethereal Yeast ??

**Comment by IceDragon200** [comment]
Place a `Culture Jar` in a `MAGICAL` biome, if you're not sure which biomes are `MAGICAL` you can enable `Enable Game Registry Dump` in the `growthcraft/core.cfg` then look at the `dumps/Biomes_dump.txt` for one.

You'll need to add some `YOUNG` fluid to the jar for yeast generation to begin, you must monitor the jar since it will randomly create a yeast if it's empty; if it has any yeast present it will start duplicating it at the cost of fluid.
