### ISSUE TITLE
[1.7.10] All the pressed cheeses turn into cheddar if piped in to the cheese press. 

### ISSUE THREAD

**Issue by cheesealmighty** [GrowthcraftCE/Growthcraft-1.7#458]
I'm trying to automate the cheese production at the moment, as a fun project.

But it seems like if you pipe/hopper in the cheese to the cheese press, the drained curds turn into cheddar cheese when it is waxed. Same issue occurs with vanilla hoppers.

They work fine if they're manually put in.  (I'll activate debugging mode and post it here.)

Any idea why?

Edit: Oh biscuits. Can't find where it is outputting the logs.

Edit 2: Opencomputers robots seem to be unaffected by this. They work fine.

Edit 3: Nope, the behaviour is somewhat erratic. Can't exactly pinpoint what is causing it.

Edit 4: Okay, for reference: https://ocdoc.cil.li/api:robot
  Using `robot.drop([count: number])` doesn't work, probably because this simulates hopper/pipe behaviour.
  Using `robot.use([side: number[, sneaky: boolean[, duration: number]]])` does work. Probably since it uses a fakeplayer.

So this script works with cheese press: https://paste.ubuntu.com/p/QTdHKbk3sT/

**Comment by IceDragon200** [comment]
An issue is how we determine cheese types from curds, the information is stored in the NBT data, if that data gets lost at any point it would revert to cheddar.

Another issue is, cheese production was meant to be manual, never automated, so I expect all kinds of oddities, but just for you, I'll try to look into it over the week, do remind me if I don't respond by Saturday

**Comment by cheesealmighty** [comment]
Yup, I assumed cheddar was the default/fallback value. 

And yup, been following this mod for years, I love the simulated hobby sort of vibe of it. But I just wanted to challenge myself trying to automate something that wasn't meant to be automated. Which actually did work at the end, see here: https://www.reddit.com/r/feedthebeast/comments/95192v/1710_fully_automated_growthcraft_cheese_factory/

> but just for you, I'll try to look into it over the week, do remind me if I don't respond by Saturday

Much appreciated, thanks. Will do.

**Comment by IceDragon200** [comment]
Okay I've looked at it, and checked the referenced issue:

## Notes

* Yep, we use custom code to set the tile entity's state from the item, unless there is a formal way of doing this, I don't think I can fix it
* Ran a "pipe cheese curds into inventory" test by just piping it all over the place (had an accident that spewed said curds all over the place, but that's a different story), I can confirm that Buildcraft pipes will keep the curd's state
* I forgot that cheese presses already works with redstone (a derp from not looking at the code for almost a year or so), so I don't need to fix that.

## Changes

* I've added all the cheese block stages to the creative tab now, so that should make it easier for testing.

Sorry I couldn't do much more :(

**Comment by cheesealmighty** [comment]
Oh. No problem. Thanks for looking into it. :)
