### ISSUE TITLE
GrowthcraftSugarcane Mod

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#8]
One who makes syrup is a "sugar maker". Temporary name or permanent name of the mod to handle the syrups.

**Comment by Sunconure11** [comment]
I have come up with a name for this module. Growthcraft Sugarcane. I also created a few new pages for concepts I thought of, but, I'll add onto them later.

**Comment by SynfulChaot** [comment]
Would brewing alcohol from sugar necessarily require another mod?  Sugar is a vanilla crop and Cellar currently handles most of the brewing.  Most of the other existent modules, IIRC, are there to add a new crop or resource, and their related acquisition mechanics, that aren't in the game already.

**Comment by Sunconure11** [comment]
Hm, it actually could fit into cellar. If distillery is merged with cellar, wormwood could fit into it as well.

**Comment by Ar97x** [comment]
I think so. Do you think on making absinthe be more susceptible to apply
the "drunk" effect?
Em 25/07/2015 23:30, "Joseph Caleb Jones" notifications@github.com
escreveu:

**Comment by Sunconure11** [comment]
Heavily alcoholic drinks will apply tipsy more frequently. Vodka, Tequila and Absinthe are examples of this.

I have not learned java yet, so, I'll be creating concepts, textures and models. However, I should be free enough to learn it soon.

**Comment by Ar97x** [comment]
Right. I don't know if this were in the mod before.

**Comment by Sunconure11** [comment]
Since wormwood will grow like generic crops in vanilla, I will likely pull off the texture for that first. I'll have to make textures and models for other crops to texture those, since a lot of them do not grow in generic fashions.

The color for the drinks and fluid is determined by the code, so, I'd have to send the appropriate decimal code over. Which I have.

Agave cores will be 3D blocks, but, I am unsure as how to approach the crop yet. Custom 3D models for each stage might not be practical, I'd probably see if something like the grapes can be done. However, if Villager's Nose could do it, I suppose I could experiment with it.

I am considering non-alcoholic and lightly alcoholic drinks for the superfood module (another concept of mine), since it focuses around the use of a juicer. I'm contemplating the possibility of Kombucha, and other forms of fermented tea. However, since they will not be created via fermentation in the barrel, or the distillery, I'm going to have to figure out the mechanics for these drinks.

**Comment by SynfulChaot** [comment]
Hmm ... perhaps Wormwood could still be separate from Cellar as it is a new distinct crop.

**Comment by Ar97x** [comment]
Maybe the process of making it absinthe could be on cellar and the crop
part on a separate mod, just like the old crops

**Comment by Ar97x** [comment]
Apple, Rice and other stuff I mean

**Comment by Sunconure11** [comment]
Hm, perhaps, I'll research into wormwood plants a bit more to see if I can make the crops stand out.

**Comment by Sunconure11** [comment]
Closing as it might be covered partially by a future module
