### ISSUE TITLE
WAILA Integration?

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#96]
Open for discussion, and does anyone know if we have external mods doing this?

I've messed with WAILA a bit with my own mod and thought "why not add this to growthcraft as well"

**Comment by Ar97x** [comment]
I can test it, would be nice to see the maturity of the crops and the
liquids in the barrels, at least.

**Comment by IceDragon200** [comment]
@Ar97x Here are some screenshots of what I've done so far
https://www.dropbox.com/sh/76chacjbpfl6av9/AAArEq3cWAHI5M8KIBbFUA2Va?dl=0

I'm still working out the architecture (its not just pushing strings into a list, but wait, it is D:)

**Comment by labpaw** [comment]
@IceDragon200 can you add %s tag to this [string](https://github.com/alatyami/Growthcraft-1.7/blob/waila-handlers/src/resources/assets/grccore/lang/en_US.lang#L18), please? So, I can swap fluid name with amount of fluid. Also, change localization in en_US.lang to "mB of" instead of just "mB". Overall, looks good :+1:

**Comment by IceDragon200** [comment]
@Adaptivity So I should change it to `mB of %s`?
Too bad to we don't have named parameters, so I could do things like this
`%<unit>s of %<fluid>s`

**Comment by IceDragon200** [comment]
Merged, so :door:
